//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientManageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentManage
    {
        public int RefPid { get; set; }
        public int RefDid { get; set; }
        public System.DateTime AppointmentStartDate { get; set; }
        public Nullable<System.DateTime> AppointmentEndDate { get; set; }
        public string Purpose { get; set; }
        public string Status { get; set; }
        public string DocumentUpload { get; set; }
        public string Cretedby { get; set; }
        public string Modifiedby { get; set; }
        public Nullable<System.DateTime> Creteddate { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public int Aid { get; set; }
    
        public virtual DoctorManage DoctorManage { get; set; }
        public virtual PatientManage PatientManage { get; set; }
    }
}
