//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientManageSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StaffManage
    {
        [Required]
        public int StaffId { get; set; }
        [Required]
        public string StaffName { get; set; }
        [Required]
        public string StaffPassword { get; set; }
        [Required]
        public string StaffEmail { get; set; }
        [Required]
        public string StaffContactNumber { get; set; }
        [Required]
        public string StaffDesignation { get; set; }
        [Required]
        public decimal StaffExperience { get; set; }
        [Required]
        public Nullable<bool> IsActive { get; set; }
        [Required]
        public string Cretedby { get; set; }
        [Required]
        public string Modifiedby { get; set; }
        [Required]
        public Nullable<System.DateTime> Creteddate { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
    }
}
